fa_report_admin:
    resource: '@FaReportBundle/Resources/config/routing/report_admin.yml'
    prefix:   /
    
fa_solr_pending_ad_report_admin:
    resource: "@FaReportBundle/Resources/config/routing/solr_report_admin.yml"
    prefix:   /
    