services:
    fa_report.form.type.user_report_search_admin:
        class: Fa\Bundle\ReportBundle\Form\UserReportSearchAdminType
        arguments: ['@service_container']
        tags:
            - { name: form.type, alias: fa_report_user_report_search_admin }

    fa_report.form.type.item_report_search_admin:
        class: Fa\Bundle\ReportBundle\Form\AdReportSearchAdminType
        arguments: ['@service_container']
        tags:
            - { name: form.type, alias: fa_item_report }

    fa_report.form.type.ad_enquiry_search_admin:
        class: Fa\Bundle\ReportBundle\Form\AdEnquiryReportSearchAdminType
        arguments: ['@service_container']
        tags:
            - { name: form.type, alias: fa_report_ad_enquiry_search_admin }

    fa_report.form.type.item_print_report_search_admin:
        class: Fa\Bundle\ReportBundle\Form\AdPrintReportSearchAdminType
        arguments: ['@service_container']
        tags:
            - { name: form.type, alias: fa_report_item_print_report_search_admin }

    fa_report.form.type.ppr_report_search_admin:
        class: Fa\Bundle\ReportBundle\Form\ProfilePackageRevenueReportSearchAdminType
        arguments: ['@service_container']
        tags:
            - { name: form.type, alias: fa_report_profile_package_revenue_report_search_admin }

    fa_report.form.type.automated_email_report_search_admin:
        class: Fa\Bundle\ReportBundle\Form\AutomatedEmailReportSearchAdminType
        arguments: ['@service_container']
        tags:
            - { name: form.type, alias: fa_report_automated_email_search_admin }

    fa_report.form.type.user_profile_report_search_admin:
        class: Fa\Bundle\ReportBundle\Form\UserProfileReportSearchAdminType
        arguments: ['@service_container']
        tags:
            - { name: form.type, alias: fa_report_user_profile_report_search_admin }

    fa_report.form.type.ad_feed_click_search_admin:
        class: Fa\Bundle\ReportBundle\Form\AdFeedClickSearchAdminType
        arguments: ['@service_container']
        tags:
            - { name: form.type, alias: fa_report_ad_feed_click_search_admin }
            
    fa_report.form.type.police_report_search_admin:
        class: Fa\Bundle\ReportBundle\Form\PoliceReportSearchAdminType
        arguments: ['@service_container']
        tags:
            - { name: form.type, alias: fa_police_report }