landing_page_admin:
    path:     /
    defaults: { _controller: "FaContentBundle:LandingPageAdmin:index" }

landing_page_new_admin:
    path:     /new
    defaults: { _controller: "FaContentBundle:LandingPageAdmin:new" }

landing_page_create_admin:
    path:     /create
    defaults: { _controller: "FaContentBundle:LandingPageAdmin:create" }
    requirements: { methods: post }

landing_page_edit_admin:
    path:     /{id}/edit
    defaults: { _controller: "FaContentBundle:LandingPageAdmin:edit" }

landing_page_update_admin:
    path:     /{id}/update
    defaults: { _controller: "FaContentBundle:LandingPageAdmin:update" }
    requirements: { methods: post|put }

landing_page_delete_admin:
    path:     /{id}/delete
    defaults: { _controller: "FaContentBundle:LandingPageAdmin:delete" }
    
ajax_landing_page_get_dimension_admin:
    path:     /ajax/get_dimension/{category_id}/
    defaults: { _controller: "FaContentBundle:LandingPageAdmin:ajaxGetDimension" }
    options:
        expose: true
