seo_config_admin:
    path:     /
    defaults: { _controller: "FaContentBundle:SeoConfigAdmin:index" }

seo_config_unnecessary_params:
    path:     /un-necessary-query-params/save
    defaults: { _controller: "FaContentBundle:SeoConfigAdmin:unnecessaryQueryParams" }

seo_config_url_rght_trim:
    path:     /url-right-trim/save
    defaults: { _controller: "FaContentBundle:SeoConfigAdmin:URLRightTrim" }

seo_config_unnecessary_odata_params:
    path:     /un-necessary-odata-params/save
    defaults: { _controller: "FaContentBundle:SeoConfigAdmin:unnecessaryODataParams" }

seo_config_category_alias:
    path:     /category-alias/save
    defaults: { _controller: "FaContentBundle:SeoConfigAdmin:categoryAlias" }

seo_config_filter_alias:
    path:     /filter-alias/save
    defaults: { _controller: "FaContentBundle:SeoConfigAdmin:filterAlias" }

seo_config_location_alias:
    path:     /location-alias/save
    defaults: { _controller: "FaContentBundle:SeoConfigAdmin:locationAlias" }

seo_config_region_alias:
    path:     /region-alias/save
    defaults: { _controller: "FaContentBundle:SeoConfigAdmin:regionAlias" }

seo_config_all_category_alias:
    path:     /all-category-alias/save
    defaults: { _controller: "FaContentBundle:SeoConfigAdmin:allCategoryAlias" }

seo_config_for_sale_exclusions:
    path:     /for-sale-exclusions/save
    defaults: { _controller: "FaContentBundle:SeoConfigAdmin:forSaleExclusions" }

seo_config_suggest:
    path:     /suggest
    defaults: { _controller: "FaContentBundle:SeoConfigAdmin:suggest" }

seo_config_status_toggle:
    path:     /status-toggle
    defaults: { _controller: "FaContentBundle:SeoConfigAdmin:statusToggle" }

seo_config_meta_robots:
    path:     /meta-robots/save
    defaults: { _controller: "FaContentBundle:SeoConfigAdmin:metaRobots" }

seo_config_max_dim_rules:
    path:     /max-dim-rules/save
    defaults: { _controller: "FaContentBundle:SeoConfigAdmin:maxDimRules" }

seo_config_redirects:
    path:     /redirects/save
    defaults: { _controller: "FaContentBundle:SeoConfigAdmin:redirects" }

seo_tool_sitemap_stat:
    path:     /sitemap/stat
    defaults: { _controller: "FaContentBundle:SeoConfigAdmin:sitemapStat" }

seo_tool_sitemap_update:
    path:     /sitemap/action
    defaults: { _controller: "FaContentBundle:SeoConfigAdmin:sitemapUpdate" }

homepage_category_settings:
    path: /category-settings
    defaults: { _controller: "FaContentBundle:SeoConfigAdmin:categorySettings" }

header_keyword_search_settings:
    path: /header-keyword-search/settings
    defaults: { _controller: "FaContentBundle:SeoConfigAdmin:keywordSearchSettings" }

crawl_settings:
    path: /crawl-settings
    defaults: { _controller: "FaContentBundle:SeoConfigAdmin:crawlSettings" }

lhs_filter_category_order:
    path: /lhs-filter/category-order
    defaults: { _controller: "FaContentBundle:SeoConfigAdmin:categoryDimension" }

lhs_filter_category_order_save:
    path: /lhs-filter/category-order/save
    defaults: { _controller: "FaContentBundle:SeoConfigAdmin:LHSFilterOrder" }

admin_validate_redirects_view:
    path: /validate-redirects
    defaults: { _controller: "FaContentBundle:SeoConfigAdmin:validateRedirectsView" }

admin_validate_redirects_upload:
    path: /validate-redirects/upload
    defaults: { _controller: "FaContentBundle:SeoConfigAdmin:validateRedirectsUpload" }

admin_validate_redirects:
    path: /validate-redirects/verify
    defaults: { _controller: "FaContentBundle:SeoConfigAdmin:validateRedirects" }

admin_seo_config_datatable:
    path: /data-table/data
    defaults: { _controller: "FaContentBundle:SeoConfigAdmin:dataTableConfig" }

admin_seo_config_redirects_datatable:
    path: /data-table/redirect-data
    defaults: { _controller: "FaContentBundle:SeoConfigAdmin:dataTableRedirectConfig" }

admin_seo_config_datatable_delete:
    path: /data-table/delete
    defaults: { _controller: "FaContentBundle:SeoConfigAdmin:removeRule" }

admin_seo_config_datatable_edit:
    path: /data-table/edit
    defaults: { _controller: "FaContentBundle:SeoConfigAdmin:editRule" }
    
admin_seo_config_datatable_redirectdelete:
    path: /data-table/redirectdelete
    defaults: { _controller: "FaContentBundle:SeoConfigAdmin:redirectremoveRule" }

admin_seo_config_datatable_redirectedit:
    path: /data-table/redirectedit
    defaults: { _controller: "FaContentBundle:SeoConfigAdmin:redirecteditRule" }
    
    