static_page_admin:
    path:     /
    defaults: { _controller: "FaContentBundle:StaticPageAdmin:index" }

static_page_new_admin:
    path:     /new
    defaults: { _controller: "FaContentBundle:StaticPageAdmin:new" }

static_page_create_admin:
    path:     /create
    defaults: { _controller: "FaContentBundle:StaticPageAdmin:create" }
    requirements: { methods: post }

static_page_edit_admin:
    path:     /{id}/edit
    defaults: { _controller: "FaContentBundle:StaticPageAdmin:edit" }

static_page_update_admin:
    path:     /{id}/update
    defaults: { _controller: "FaContentBundle:StaticPageAdmin:update" }
    requirements: { methods: post|put }

static_page_delete_admin:
    path:     /{id}/delete
    defaults: { _controller: "FaContentBundle:StaticPageAdmin:delete" }
