<?php

/**
 * This file is part of the fa bundle.
 *
 * @copyright Copyright (c) 2014, FMG
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

namespace Fa\Bundle\ReportBundle\Walker;

use Doctrine\ORM\Query\SqlWalker;
use Fa\Bundle\ReportBundle\Repository\AutomatedEmailReportDailyRepository;
use Doctrine\ORM\Query\AST\SelectStatement;
use Doctrine\ORM\Query;

/**
 * This is sql walker.
 *
 * This walker is used to modify the sql generated by doctrine.
 *
 * @author Amit Limbadia <amitl@aspl.in>
 * @copyright 2014 Friday Media Group Ltd
 * @version v1.0
 */
class AutomatedEmailSqlWalker extends SqlWalker
{
    /**
     * {@inheritdoc}
     */
    public function walkSelectStatement(SelectStatement $AST)
    {
        $sql = parent::walkSelectStatement($AST);
        $tablealias = $this->getSQLTableAlias($this->getEntityManager()->getClassMetadata('FaReportBundle:AutomatedEmailReportDaily')->getTableName(), AutomatedEmailReportDailyRepository::ALIAS);

        if ($this->getQuery()->getHint('automatedEmailReport.count') === true) {
            $sql = str_replace("AND a0_.id IN (?)", "", $sql);
            $sql = str_replace("DISTINCT ".$tablealias.".id)", "DISTINCT ".$tablealias.".identifier)", $sql);
            $sql = str_replace("DISTINCT ".$tablealias.".id ", "DISTINCT ".$tablealias.".identifier ", $sql);
        }

        if ($this->getQuery()->getHint('automatedEmailReport.count') === true) {
            if (strpos($sql, 'DISTINCT a0_.id AS id0, SUM(a0_.email_sent_counter) AS sclr1, SUM(a0_.email_open_counter) AS sclr2')) {
                $sql = str_replace("GROUP BY a0_.identifier", "", $sql);
                $sql = str_replace("ORDER BY sclr1 DESC", "", $sql);
            }
            $sql = str_replace("DISTINCT a0_.id AS id0, SUM(a0_.email_sent_counter) AS sclr1, SUM(a0_.email_open_counter) AS sclr2", "DISTINCT ".$tablealias.".id as id0", $sql);
        }

        return $sql;
    }
}
