<?php

/**
 * This file is part of the fa bundle.
 *
 * @copyright Copyright (c) 2014, FMG
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

namespace Fa\Bundle\UserBundle\Repository;

use Doctrine\ORM\EntityRepository;
use Fa\Bundle\CoreBundle\Manager\CommonManager;

/**
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 *
 * @author Gaurav Aggarwal <gaurav.aggarwal@fridaymediagroup.com>
 * @copyright 2018 Friday Media Group Ltd
 * @version v1.0
 */
class NewsletterFeedbackRepository extends EntityRepository
{
	/**
	 * Prepare query builder.
	 *
	 * @param array $data Array of data.
	 *
	 * @return Doctrine\ORM\QueryBuilder The query builder.
	 */
	public function getBaseQueryBuilder()
	{
		return $this->createQueryBuilder(self::ALIAS);
	}
	
	/**
	 * Get payment method options.
	 *
	 * @param object $container Container identifier.
	 *
	 * @return array
	 */
	public function getFeedbackOptions()
	{
		$optionArray = array(
				'1' => 'I received too many newsletters',
				'2' => 'The newsletters I received weren\'t relevant to me',
				'3' => 'I found the newsletter content offensive',
				'4' => 'I didn\'t know what I was signing up for',
				'5' => 'I never signed up to receive these email newsletters',
				'6' => 'Other, please specify:'
		);
		
		return $optionArray;
	}
	
}
