category_render_header_categories:
    path:     /category/render/header_categories/{is_tablet}/{is_mobile}/{location}
    defaults: { _controller: "FaEntityBundle:Category:renderHeaderCategories",  'is_tablet':0, 'is_mobile':0, 'location': null}