parameters:
#    fa_entity.example.class: Fa\Bundle\EntityBundle\Example

services:
#    fa_entity.example:
#        class: %fa_entity.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
