parameters:
#    fa_entity.example.class: Fa\Bundle\EntityBundle\Example

services:
#    fa_entity.example:
#        class: %fa_entity.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]

    fa_package_created_log:
        class: Monolog\Handler\StreamHandler
        arguments: ['%kernel.logs_dir%/%kernel.environment%.fa_package_created_log.log']
