manage_my_ads_active:
    path:     /manage_my_ads/active/
    defaults: {  _controller: FaUserBundle:ManageMyAd:index, type: active }
    requirements:
        type:  'inactive'

manage_my_ads_inactive:
    path:     /manage_my_ads/inactive/
    defaults: {  _controller: FaUserBundle:ManageMyAd:index, type: inactive }
    requirements:
        type:  'inactive'
        
manage_my_ads_boosted:
    path:     /manage_my_ads/boosted/
    defaults: {  _controller: FaUserBundle:ManageMyAd:index, type: boosted }
    requirements:
        type:  'boosted'
        
ajax_manage_my_ads_change_status:
    path:     /ajax/manage_my_ads/change_ad_status/
    defaults: { _controller: FaUserBundle:ManageMyAd:ajaxChangeAdStatus }

manage_my_ads_mark_as_sold:
    path:     /manage_my_ads/mark_as_sold/{adId}
    defaults: {  _controller: FaUserBundle:ManageMyAd:soldAd}

manage_my_ads_refresh_ad:
    path:     /manage_my_ads/refresh_ad/{adId}-{date}
    defaults: {  _controller: FaUserBundle:ManageMyAd:refreshAd}

manage_my_ads_social_share_popup:
    path:     /manage_my_ads/social_share
    defaults: {  _controller: FaUserBundle:ManageMyAd:socialShare}

ajax_manage_my_ads_get_status:
    path:     /ajax/manage_my_ads/get_status/
    defaults: { _controller: FaUserBundle:ManageMyAd:ajaxGetStatus }

ajax_manage_my_ads_boost_ad:
    path:     /ajax/manage_my_ads/boost_ad/    
    defaults: { _controller: FaUserBundle:ManageMyAd:ajaxBoostAd }
       
ajax_manage_my_ads_boost_multiple_ad:
    path:     /ajax/manage_my_ads/boost_multiple_ad/
    defaults: { _controller: FaUserBundle:ManageMyAd:ajaxBoostMultipleAd }
    
individual_upsell:
    path:   /individual_upsell/{adId}/{upsellId}
    defaults:  { _controller: "FaUserBundle:ManageMyAd:ajaxIndividualUpsell" }
    options:
        expose: true
        
paypal_payment_process_for_individual_upsell:
    path:   /paypal_payment_process_for_individual_upsell/{upsellId}/{adId}
    defaults:  { _controller: "FaUserBundle:ManageMyAd:ajaxPaypalPaymentProcessForIndividualUpsell" }
    options:
        expose: true
        
ajax_manage_my_ads_deactivate_featured:
    path:     /ajax/manage_my_ads/deactivate_featured/
    defaults: { _controller: FaUserBundle:ManageMyAd:ajaxDeactivateFeatured } 
    
credit_payment_process_for_individual_upsell:
    path:   /credit_payment_process_for_individual_upsell/{upsellId}/{adId}
    defaults:  { _controller: "FaUserBundle:ManageMyAd:ajaxCreditPaymentProcessForIndividualUpsell" }
    options:
        expose: true
               

