<?php

/**
 * This file is part of the fa bundle.
 *
 * @copyright Copyright (c) 2014, FMG
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

namespace Fa\Bundle\AdBundle\Walker;

use Doctrine\ORM\Query\SqlWalker;

/**
 * This is sql walker.
 *
 * This walker is used to modify the sql generated by doctrine.
 *
 * @author Sagar lotiya  <sagar@aspl.in>
 * @copyright 2014 Friday Media Group Ltd
 * @version v1.0
 */
class AdAdminSearchSqlWalker extends SqlWalker
{
    /**
     * Walks down a walkFromClause AST node, thereby generating the appropriate SQL.
     *
     * @param $fromClause
     *
     * @return string The SQL.
     */
    public function walkFromClause($fromClause)
    {
        $sql = parent::walkFromClause($fromClause);

        if ($this->getQuery()->getHint('adAdminSearchSqlWalker.userIndex') === true) {
            $sql = preg_replace("/LEFT JOIN user\s(.*)_\s/", "LEFT JOIN user $1_ USE INDEX (fa_user_user_first_name_index, fa_user_user_last_name_index, fa_user_user_email_index, fa_user_user_phone_index, fa_user_user_paypal_email_index) ", $sql);
        }

        if ($this->getQuery()->getHint('adAdminSearchSqlWalker.categoryIndex') === true) {
            $sql = preg_replace("/LEFT JOIN category\s(.*)_\s/", "LEFT JOIN category $1_ USE INDEX (fa_entity_category_name_index) ", $sql);
        }

        if ($this->getQuery()->getHint('adAdminSearchSqlWalker.locationIndex') === true) {
            $sql = preg_replace("/LEFT JOIN location\s(.*)_\s/", "LEFT JOIN location $1_ USE INDEX (fa_entity_location_name_index) ", $sql);
        }

        return $sql;
    }
}
