fa_dotmailer_homepage:
    path:     /dotmailer
    defaults: { _controller: FaDotMailerBundle:Default:index }

fa_dotmailer_createdatafield:
    path:     /dotmailer/createdatafield
    defaults: { _controller: FaDotMailerBundle:Default:create }

fa_dotmailer_createaddressbook:
    path:     /dotmailer/createaddressbook
    defaults: { _controller: FaDotMailerBundle:Default:create }
