redirect_Jobs:
    path: /Jobs
    host: '%fa.main.host%'
    defaults:
        _controller: FrameworkBundle:Redirect:redirect
        route: fa_frontend_homepage
        permanent: true
        ignoreAttributes: true

redirect_Classifieds:
    path: /InternationalClassifieds
    host: '%fa.main.host%'
    defaults:
        _controller: FrameworkBundle:Redirect:redirect
        route: fa_frontend_homepage
        permanent: true
        ignoreAttributes: true

redirect_Reasons:
    path: /Reasons
    host: '%fa.main.host%'
    defaults:
        _controller: FrameworkBundle:Redirect:redirect
        route: fa_frontend_homepage
        permanent: true
        ignoreAttributes: true

redirect_popular-searches:
    path: /popular-searches{page_string}
    host: '%fa.main.host%'
    defaults:
        _controller: FrameworkBundle:Redirect:redirect
        route: fa_frontend_homepage
        permanent: true
        ignoreAttributes: true
    requirements:
      page_string: ".+"

redirect_Recycling:
    path: /Recycling
    host: '%fa.main.host%'
    defaults:
        _controller: FrameworkBundle:Redirect:redirect
        route: fa_frontend_homepage
        permanent: true
        ignoreAttributes: true

redirect_motor_change_location:
  path: /change-location
  defaults:
        _controller: FrameworkBundle:Redirect:redirect
        route: fa_frontend_homepage
        permanent: true
        ignoreAttributes: true
  host: '%fa.motor.host%'

redirect_for_sale_change_location:
  path: /change-location
  defaults:
        _controller: FrameworkBundle:Redirect:redirect
        route: fa_frontend_homepage
        permanent: true
        ignoreAttributes: true
  host: '%fa.main.host%'

redirect_article1:
  path: /article/
  defaults: { _controller: FaFrontendBundle:Default:articleRedirect }
  host: '%fa.main.host%'

redirect_article2:
  path: /article/
  defaults: { _controller: FaFrontendBundle:Default:articleRedirect }
  host: '%fa.motor.host%'
      
redirect_article:
  path: /article/{page_string}
  defaults: { _controller: FaFrontendBundle:Default:articleRedirect }
  host: '%fa.main.host%'
  requirements:
      page_string: ".+"
      
redirect_topic:
  path: /topic/{page_string}
  defaults: { _controller: FaFrontendBundle:Default:articleRedirect }
  host: '%fa.main.host%'
  requirements:
      page_string: ".+"
      
motor_redirect_article:
  path: /article/{page_string}
  defaults: { _controller: FaFrontendBundle:Default:articleRedirect }
  host: '%fa.motor.host%'
  requirements:
      page_string: ".+"
      
motor_redirect_topic:
  path: /topic/{page_string}
  defaults: { _controller: FaFrontendBundle:Default:articleRedirect }
  host: '%fa.motor.host%'
  requirements:
      page_string: ".+"
      
redirect_change_location:
  path: /change-location/{location}
  defaults: { _controller: FaFrontendBundle:Default:redirectToLocationPage }
  host: '%fa.main.host%'

redirect_old_category_slug_change_location:
  path: /{location}/{old_cat_slug}
  defaults: { _controller: FaFrontendBundle:Default:redirectOldCategorySlugChange }
  host: '%fa.main.host%'
  requirements:
        old_cat_slug: "(.*)house-rubbish-clearance(.*)|(.*)non-digital-cameras(.*)|(.*)farming-wanted(.*)"
        
redirect_urgent_2:
  path: /{location}/urgent/{page_string}
  defaults: { _controller: FaFrontendBundle:Default:changeLocation }
  host: '%fa.main.host%'
  requirements:
      page_string: ".+"
      
redirect_urgent_1:
  path: /{location}/urgent-property-rentals{page_string}
  defaults: { _controller: FaFrontendBundle:Default:changeLocation }
  host: '%fa.main.host%'
  requirements:
      page_string: ".+"

redirect_popular-searches_2:
  path: /{location}/popular-searches/{page_string}
  defaults: { _controller: FaFrontendBundle:Default:changeLocation }
  host: '%fa.main.host%'
  requirements:
      page_string: ".+"

redirect_popular:
  path: /{location}/popular
  defaults: { _controller: FaFrontendBundle:Default:changeLocation }
  host: '%fa.main.host%'

redirect_BuyingABicycle:
    path: /StaySafe/{SafeSection}
    host: '%fa.main.host%'
    defaults:
        _controller: FrameworkBundle:Redirect:urlRedirect
        path: /stay-safe-help/
        permanent: true
    requirements:
        SafeSection: "^(|BuyingABicycle|BuyingACar|BuyingAndSellingSafely|BuyingAPet|BuyingSafely|FAQ|FindingAJobSafely|HolidayAndTravel|Property|ProtectYourselfFromScamEmails|ReportingProblemsToThePolice|SellingSafely|Services|WatchOutForOnlineScams)$"

redirect_motor_my_account:
  path: /MyAccount
  defaults:
      _controller: FrameworkBundle:Redirect:redirect
      route: my_account
      permanent: true
      ignoreAttributes: true
  host: '%fa.motor.host%'
  
redirect_auto_email:
  path: /Emails/Tracking/
  defaults: { _controller: FaFrontendBundle:Default:redirectEmail }
  host: '%fa.main.host%'

redirect_auto_email2:
  path: /Emails/Tracking
  defaults: { _controller: FaFrontendBundle:Default:redirectEmail }
  host: '%fa.main.host%'
  
redirect_for_about_us:
  path: /AboutUs.asp/
  defaults:
        _controller: FrameworkBundle:Redirect:urlRedirect
        path: /about-us/
        permanent: true
  host: '%fa.main.host%'

redirect_for_old_jobs:
  path: /jobs.asp/
  defaults:
        _controller: FrameworkBundle:Redirect:urlRedirect
        path: /uk/jobs/
        permanent: true
  host: '%fa.main.host%'

redirect_loginRegister:
  path: LogInRegister.asp/
  defaults:
        _controller: FrameworkBundle:Redirect:urlRedirect
        path: /login/
        permanent: true
  host: '%fa.main.host%'
  
redirect_motors_cars-under-1000:
  path: /motors/cars-under-1000/
  defaults:
        _controller: FrameworkBundle:Redirect:urlRedirect
        path: /uk/motors/cars-under-1000/
        permanent: true
  host: '%fa.main.host%'

redirect_motors_sedgebrook:
  path: /motors/sedgebrook/
  defaults:
        _controller: FrameworkBundle:Redirect:urlRedirect
        path: /motors/sedgebrook-grantham/
        permanent: true
  host: '%fa.main.host%'

redirect_MySavedSearches:
  path: /MySavedSearches/
  defaults:
        _controller: FrameworkBundle:Redirect:urlRedirect
        path: /search_agent/list/
        permanent: true
  host: '%fa.main.host%'
  
redirect_NewTermsAndConditions:
  path: /NewTermsAndConditions.asp/
  defaults:
        _controller: FrameworkBundle:Redirect:urlRedirect
        path: /terms-and-conditions/
        permanent: true
  host: '%fa.main.host%'

redirect_PlaceAnAd_LogIn:
  path: /PlaceAnAd/LogIn.asp/
  defaults:
        _controller: FrameworkBundle:Redirect:urlRedirect
        path: /paa/first_step
        permanent: true
  host: '%fa.main.host%'
  
redirect_PlaceAnAd:
  path: /PlaceAnAd/
  defaults:
        _controller: FrameworkBundle:Redirect:urlRedirect
        path: /paa/first_step
        permanent: true
  host: '%fa.main.host%'
  
redirect_PlaceAnAdIndex:
  path: /PlaceAnAd/Index.asp/
  defaults:
        _controller: FrameworkBundle:Redirect:urlRedirect
        path: /paa/first_step
        permanent: true
  host: '%fa.main.host%'
  
redirect_Privacycookiepolicy:
  path: /Privacycookiepolicy.asp/
  defaults:
        _controller: FrameworkBundle:Redirect:urlRedirect
        path: /cookies-policy/
        permanent: true
  host: '%fa.main.host%'

redirect_Car-Auctions-in-Crawley:
  path: /search/Car-Auctions-in-Crawley/
  defaults:
        _controller: FrameworkBundle:Redirect:urlRedirect
        path: /crawley/motors/cars/
        permanent: true
  host: '%fa.main.host%'
  
redirect_sell-my-furniture:
  path: /sell-my-furniture/
  defaults:
        _controller: FrameworkBundle:Redirect:urlRedirect
        path: /sell-my-bedroom-furniture/
        permanent: true
  host: '%fa.main.host%'

redirect_sell-your-stuff:
  path: /sell-your-stuff/
  defaults:
        _controller: FrameworkBundle:Redirect:urlRedirect
        path: /sell-my-stuff/
        permanent: true
  host: '%fa.main.host%'

redirect_signin:
  path: /signin/
  defaults:
        _controller: FrameworkBundle:Redirect:urlRedirect
        path: /login/
        permanent: true
  host: '%fa.main.host%'

redirect_ukescorts:
  path: /uk/escorts/
  defaults:
        _controller: FrameworkBundle:Redirect:urlRedirect
        path: /uk/adult-services/escorts/
        permanent: true
  host: '%fa.main.host%'

redirect_Retail-Jobs-in-Worthing:
  path: /uk/Retail-Jobs-in-Worthing/
  defaults:
        _controller: FrameworkBundle:Redirect:urlRedirect
        path: /worthing/jobs/retail-jobs/
        permanent: true
  host: '%fa.main.host%'
  
redirect_videos-and-n-tyres:
  path: /video/s-and-n-tyres-motor-racing-video/
  defaults:
        _controller: FrameworkBundle:Redirect:urlRedirect
        path: https://blog.friday-ad.co.uk/
        permanent: true
  host: '%fa.main.host%'

redirect_VideoCompetition:
  path: /VideoCompetition.asp/
  defaults:
        _controller: FrameworkBundle:Redirect:urlRedirect
        path: https://blog.friday-ad.co.uk/competitions/
        permanent: true
  host: '%fa.main.host%'

redirect_win-shopping-vouchers:
  path: /win-shopping-vouchers/
  defaults:
        _controller: FrameworkBundle:Redirect:urlRedirect
        path: https://blog.friday-ad.co.uk/competitions/
        permanent: true
  host: '%fa.main.host%'
  
redirect_Christmas:
  path: /ChristmasWishesEntry.asp/
  defaults:
        _controller: FrameworkBundle:Redirect:urlRedirect
        path: https://blog.friday-ad.co.uk/competitions/
        permanent: true
  host: '%fa.main.host%'
  
redirect_uk_Car-Auctions-in-Crawley:
  path: /uk/Car-Auctions-in-Crawley/
  defaults:
        _controller: FrameworkBundle:Redirect:urlRedirect
        path: /uk/motors/cars/
        permanent: true
  host: '%fa.main.host%'

redirect_1z13zwl:
  path: /uk/used-caravans-and-motorhomes-for-sale/motorhomes-n-1z13zwl/
  defaults:
        _controller: FrameworkBundle:Redirect:urlRedirect
        path: /uk/motors/motorhomes-caravans/motorhomes/
        permanent: true
  host: '%fa.main.host%'
  
redirect_1z0usth:
  path: /advertiser/rogate-garage-N-1z0usth
  defaults:
        _controller: FrameworkBundle:Redirect:urlRedirect
        path: /business/rogate-garage/
        permanent: true
  host: '%fa.motor.host%'
  
redirect_1z0uumt:
  path: /advertiser/vale-motorcycles-N-1z0uumt
  defaults:
        _controller: FrameworkBundle:Redirect:urlRedirect
        path: /business/vale-motorcycles/
        permanent: true
  host: '%fa.motor.host%'

redirect_1z141fd:
  path: /uk/services/building-home-services/builders-n-1z141fd/
  defaults:
        _controller: FrameworkBundle:Redirect:urlRedirect
        path: /uk/services/property-home-services/builders/
        permanent: true
  host: '%fa.main.host%'
  
redirect_N-1z1419o:
  path: /warwick/N-1z1419o/
  defaults:
        _controller: FrameworkBundle:Redirect:urlRedirect
        path: /uk/animals/pets/dogs-puppies/bichon-frise/
        permanent: true
  host: '%fa.main.host%'

redirect_for_advertise_sell:
  path: /{redirection_old}
  host: '%fa.main.host%'
  defaults:
      _controller: FrameworkBundle:Redirect:redirect
      route: fa_frontend_homepage
      permanent: true
      ignoreAttributes: true
  requirements:
      redirection_old: "(|advertise/sell-your-stuff-new/|topic/jobs-in-sussex/|advertise/sell-your-stuff/|buyonline.asp|Category/5/Web/Channel.asp/|changeEdition.asp|ChristmasWishesList.asp|Class/4620/Web/SearchResults.asp/|FADDealerList.asp|Help.asp|international-classifieds.asp|PrintVoucherTI.asp|Scam.asp|SearchResults.asp|sellonline.asp|siteindex.asp|SiteIndex/|tips-for-interviewing/index.asp/|VoucherDetailsTI.asp|VoucherSearchResultsWB.asp)"

redirect_Welcome:
    path: /Welcome.htm
    host: '%fa.main.host%'
    defaults:
        _controller: FrameworkBundle:Redirect:redirect
        route: fa_frontend_homepage
        permanent: true
        ignoreAttributes: true

redirect_HomeNEW:
    path: /HomeNEW.asp
    host: '%fa.main.host%'
    defaults:
        _controller: FrameworkBundle:Redirect:redirect
        route: fa_frontend_homepage
        permanent: true
        ignoreAttributes: true