<?php

/**
 * This file is part of the fa bundle.
 *
 * @copyright Copyright (c) 2014, FMG
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

namespace Fa\Bundle\TiReportBundle\Walker;

use Doctrine\ORM\Query\SqlWalker;

/**
 * This is sql walker.
 *
 * This walker is used to modify the sql generated by doctrine.
 *
 * @author Amit Limbadia <amitl@aspl.in>
 * @copyright 2014 Friday Media Group Ltd
 * @version v1.0
 */
class AdFeedClickReportSqlWalker extends SqlWalker
{
    /**
     * {@inheritdoc}
     */
    public function walkWhereClause($whereClause)
    {
        $sql = parent::walkWhereClause($whereClause);

        if ($this->getQuery()->getHint('adFeedClickReportRemoveId.ad_id') === true) {
            $sql = str_replace("AND a0_.id IN (?)", "AND a0_.ad_id IN (?)", $sql);
        }

        if ($this->getQuery()->getHint('adFeedClickReportRemoveId.ad_feed_site_id') === true) {
            $sql = str_replace("AND a0_.id IN (?)", "AND a0_.ad_feed_site_id IN (?)", $sql);
        }
        
        return $sql;
    }
    
    /**
     * Walks down a walkFromClause AST node, thereby generating the appropriate SQL.
     *
     * @param $fromClause
     *
     * @return string The SQL.
     */
    public function walkSelectClause($selectClause)
    {
        $sql = parent::walkSelectClause($selectClause);
        if ($this->getQuery()->getHint('adFeedClickReportRemoveId.ad_id') === true) {
            $sql = str_replace("SELECT count(DISTINCT a0_.id) AS sclr0", "SELECT count(DISTINCT a0_.ad_id) AS sclr0", $sql);
        }

        if ($this->getQuery()->getHint('adFeedClickReportRemoveId.ad_id') === true) {
            $sql = str_replace("SELECT DISTINCT a0_.id AS id0", "SELECT DISTINCT a0_.ad_id AS id0", $sql);
        }

        if ($this->getQuery()->getHint('adFeedClickReportRemoveId.ad_feed_site_id') === true) {
            $sql = str_replace("SELECT count(DISTINCT a0_.id) AS sclr0", "SELECT count(DISTINCT a0_.ad_feed_site_id) AS sclr0", $sql);
        }
      
        if ($this->getQuery()->getHint('adFeedClickReportRemoveId.ad_feed_site_id') === true) {
            $sql = str_replace("SELECT DISTINCT a0_.id AS id0", "SELECT DISTINCT a0_.ad_feed_site_id AS id0", $sql);
        }
      
        return $sql;
    }
}
