<?php

namespace Fa\Bundle\FrontendBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * Fa\Bundle\FrontendBundle\Repository\AdultHomepageRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AdultHomepageRepository extends EntityRepository
{
    use \Fa\Bundle\CoreBundle\Search\Search;

    const EXTERNAL_BLOG_URL1 = 'https://punter.friday-ad.co.uk';
    const EXTERNAL_BLOG_URL2 = 'https://adult.friday-ad.co.uk';
    const EXTERNAL_BLOG_BTN1 = 'Adult punter blog';
    const EXTERNAL_BLOG_BTN2 = 'Adult workers blog';
}
?>
