parameters:
    fa.report.createdatafield.class: Fa\Bundle\ReportBundle\Resource\CreateDataField

services:
    fa.report.createdatafield.resource:
        class: '%fa.report.createdatafield.class%'
        arguments: ['@service_container']
        
    ti_package_created_log:
        class: Monolog\Handler\StreamHandler
        arguments: ['%kernel.logs_dir%/%kernel.environment%.ti_package_created_log.log']
        