services:
    fa_ad.entity_listener.ad:
        class: Fa\Bundle\AdBundle\Listener\AdListener
        arguments: [ '@service_container' ]
        tags:
            -  { name: doctrine.entity_listener }

    fa_ad.entity_listener.paa_field_rule:
        class: Fa\Bundle\AdBundle\Listener\PaaFieldRuleListener
        arguments: [ '@service_container' ]
        tags:
            -  { name: doctrine.entity_listener }
            
    fa_ad.entity_listener.ad_favorite:
        class: Fa\Bundle\AdBundle\Listener\AdFavoriteListener
        arguments: [ '@service_container' ]
        tags:
            -  { name: doctrine.entity_listener }
            
    fa_ad.entity_listener.ad_image:
        class: Fa\Bundle\AdBundle\Listener\AdImageListener
        arguments: [ '@service_container' ]
        tags:
            -  { name: doctrine.entity_listener }

    fa_ad.entity_listener.paa_lite_field_rule:
        class: Fa\Bundle\AdBundle\Listener\PaaLiteFieldRuleListener
        arguments: [ '@service_container' ]
        tags:
            -  { name: doctrine.entity_listener }