ajax_ad_image_save_admin:
    path:     /ajax/save_image
    defaults: { _controller: FaAdBundle:AdImage:ajaxSaveUploadedImage }

ajax_get_ad_images_admin:
    path:     /ajax/get_image
    defaults: { _controller: FaAdBundle:AdImage:ajaxRenderUploadedImage }

ajax_delete_ad_images_admin:
    path:     /ajax/delete_image/{adId}/{imageId}/{imageHash}/{vertical}
    defaults: { _controller: FaAdBundle:AdImage:ajaxDeleteImage }

ajax_get_big_ad_image_admin:
    path:     /ajax/get_big_image/{adId}/{imageId}/{imageHash}
    defaults: { _controller: FaAdBundle:AdImage:ajaxGetBigImage }
    
ajax_crop_ad_image_admin:
    path:     /ajax/crop_image/{adId}/{imageId}/{imageHash}
    defaults: { _controller: FaAdBundle:AdImage:ajaxCropImage }

ajax_change_ad_image_order_admin:
    path:     /ajax/change_image_order/{adId}
    defaults: { _controller: FaAdBundle:AdImage:ajaxChangeAdImageOrder }

ajax_make_main_image_admin:
    path:     /ajax/make_main_image/{adId}
    defaults: { _controller: FaAdBundle:AdImage:ajaxMakeMainImage }

ajax_reset_ad_image_admin:
    path:     /ajax/reset_image/{adId}/{imageId}/{imageHash}/{vertical}
    defaults: { _controller: FaAdBundle:AdImage:ajaxResetImage }
