search_keyword_admin:
    path:     /
    defaults: { _controller: "FaAdBundle:SearchKeywordAdmin:index" }
    
search_keyword_edit_admin:
    path:     /{id}/edit
    defaults: { _controller: "FaAdBundle:SearchKeywordAdmin:edit" }

search_keyword_update_admin:
    path:     /{id}/update
    defaults: { _controller: "FaAdBundle:SearchKeywordAdmin:update" }
    requirements: { methods: post|put }

search_keyword_upload_csv_admin:
    path:     /upload_csv
    defaults: { _controller: "FaAdBundle:SearchKeywordAdmin:uploadCsv" }

search_keyword_import_keywords_admin:
    path:     /import_keywords
    defaults: { _controller: "FaAdBundle:SearchKeywordAdmin:importKeywords" }

search_keyword_process_keywords_admin:
    path:     /process_keywords
    defaults: { _controller: "FaAdBundle:SearchKeywordAdmin:processKeywords" }

search_keyword_delete_admin:
    path:     /{id}/delete
    defaults: { _controller: "FaAdBundle:SearchKeywordAdmin:delete" }